name: Deploy Static Site to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies (if needed)
        run: npm install  # Solo si usas Node.js o un gestor de paquetes

      - name: Build project (if needed)
        run: npm run build  # Solo si necesitas compilar tu aplicación

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nombre-de-tu-app-service'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
